# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi
from PyQt5.QtCore import QEasingCurve, QRect, Qt
from PyQt5.QtCore import (
    QPropertyAnimation, QSequentialAnimationGroup, QPoint, QSize)
from subprocess import run
import pymsgbox
from time import sleep


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 561)
        Dialog.setStyleSheet("border-radius: 0.0001px;\n"
"background-image: url(/home/alihv3000/Desktop/New Folder/bglogin.jpg);")
        Dialog.setMinimumSize(700, 561)
        Dialog.setMaximumSize(700, 561)
        Dialog.setWindowFlags(Qt.FramelessWindowHint)
        #Dialog.setAttribute(Qt.WA_TranslucentBackground)
        self.treeView = QtWidgets.QTreeView(Dialog)
        self.treeView.setGeometry(QtCore.QRect(165, 112, 371, 341))
        self.treeView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"background-image:url()\n"
"")
        self.treeView.setObjectName("treeView")
        self.treeView_2 = QtWidgets.QTreeView(Dialog)
        self.treeView_2.setGeometry(QtCore.QRect(165, 112, 371, 61))
        self.treeView_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(120, 2, 255, 255), stop:0.166 rgba(120, 2, 255, 255), stop:0.333 rgba(85, 0, 255, 255), stop:0.5 rgba(85, 0, 255, 255), stop:0.666 rgba(57, 7, 255, 255), stop:0.833 rgba(57, 7, 255, 255), stop:1 rgba(57, 7, 255, 255));\n"
"\n"
"border-radius: 0.001px;\n"
"background-image:url()")
        self.treeView_2.setObjectName("treeView_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(305, 122, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(); \n"
"background-image:url()")
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setGeometry(QtCore.QRect(275, 210, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.username.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.username.setStyleSheet("background-color: rgb(255,255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url();\n"
"border :1px solid rgb(62,62,62);\n"
"border-top-left-radius :20px;\n"
"border-bottom-left-radius : 20px; \n"
"border-top-right-radius : 20px; \n"
"border-bottom-right-radius : 20px;")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(275, 260, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password.setStyleSheet("background-color: rgb(255,255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url();\n"
"border :1px solid rgb(62,62,62);\n"
"border-top-left-radius :20px;\n"
"border-bottom-left-radius : 20px; \n"
"border-top-right-radius : 20px; \n"
"border-bottom-right-radius : 20px;")
        self.password.setText("")
        self.password.setObjectName("password")
        self.remember = QtWidgets.QCheckBox(Dialog)
        self.remember.setGeometry(QtCore.QRect(225, 320, 131, 25))
        self.remember.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"background-image:url();\n"
"color: rgb(0, 0, 0);")
        self.remember.setObjectName("remember")
        self.log_in = QtWidgets.QPushButton(Dialog)
        self.log_in.setGeometry(QtCore.QRect(265, 362, 181, 41))
        self.log_in.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_in.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(120, 2, 255, 255), stop:0.166 rgba(120, 2, 255, 255), stop:0.333 rgba(85, 0, 255, 255), stop:0.5 rgba(85, 0, 255, 255), stop:0.666 rgba(57, 7, 255, 255), stop:0.833 rgba(57, 7, 255, 255), stop:1 rgba(57, 7, 255, 255));\n"
"\n"
"border-radius: 20px;\n"
"background-image:url();\n"
"")
        self.log_in.setObjectName("log_in")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(275, 412, 111, 24))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(195, 220, 81, 19))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(198, 270, 81, 19))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_6.setObjectName("label_6")
        self.forgot = QtWidgets.QPushButton(Dialog)
        self.forgot.setGeometry(QtCore.QRect(362, 320, 131, 27))
        self.forgot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot.setStyleSheet("color: rgb(85, 0, 127);\n"
"background-image:url()")
        self.forgot.setObjectName("forgot")
        self.signup = QtWidgets.QPushButton(Dialog)
        self.signup.setGeometry(QtCore.QRect(380, 410, 61, 27))
        self.signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup.setStyleSheet("color: rgb(85, 0, 127);\n"
"background-image:url()")
        self.signup.setObjectName("signup")
        self.incorrect = QtWidgets.QLabel(Dialog)
        self.incorrect.setObjectName("incorrect")
        self.incorrect.setGeometry(QtCore.QRect(220, 180, 271, 20))
        self.incorrect.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-image:url()")
        self.incorrect.hide()
        self.close = QtWidgets.QPushButton(Dialog)
        self.close.setObjectName("close")
        self.close.setGeometry(QRect(655, 12, 32, 32))
        self.close.setCursor(QtGui.QCursor(Qt.PointingHandCursor))
        self.close.setStyleSheet("border-radius: 16px;\n"
"background-image: url(/home/alihv3000/Documents/py/close-button.png);")
        self.minimize = QtWidgets.QPushButton(Dialog)
        self.minimize.setObjectName(u"minimize")
        self.minimize.setGeometry(QRect(615, 13, 32, 32))
        self.minimize.setCursor(QtGui.QCursor(Qt.PointingHandCursor))
        self.minimize.setStyleSheet("border-radius: 16px;\n"
"background-image: url(/home/alihv3000/Documents/py/mini.png);")
        self.tryrem = QtWidgets.QPushButton(Dialog)
        self.tryrem.setObjectName("tryrem")
        self.tryrem.setGeometry(QRect(-133, -43, 151, 41))
        self.tryrem.setStyleSheet("background-image: url();\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius: 20px")
        self.tryrem.show()

        self.retranslateUi(Dialog)
        self.log_in.clicked.connect(self.login)
        self.forgot.clicked.connect(self.forgot_pass)
        self.signup.clicked.connect(self.executeLoginPage)
        self.close.clicked.connect(Dialog.close)
        self.minimize.clicked.connect(Dialog.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def login(self):
        username = self.username.text()
        password = self.password.text()
        
        if username != 'username' or password != 'password':
            self.incorrect.setText('The Username or Password is incorrect !')
            self.incorrect.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-image:url()")
            self.incorrect.setGeometry(QtCore.QRect(220, 180, 271, 20))
            self.incorrect.show()
        else:
            self.incorrect.setText('You are in !')
            self.incorrect.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-image:url()")
            self.incorrect.setGeometry(QtCore.QRect(320, 180, 271, 20))
            self.incorrect.show()
            
    def forgot_pass(self):
        #self.tryrem.show()
        self.anim = QPropertyAnimation(self.tryrem, b"pos")
        self.anim.setEasingCurve(QEasingCurve.OutInCubic)
        self.anim.setStartValue(QPoint(-133, -43))
        self.anim.setEndValue(QPoint(690, 560))
        self.anim.setDuration(3000)
        self.anim.finished.connect(self.anim.deleteLater)
        self.anim.start()
#         self.tryrem = QtWidgets.QPushButton(Dialog)
#         self.tryrem.setObjectName("tryrem")
#         self.tryrem.setGeometry(QRect(-133, -43, 151, 41))
#         self.tryrem.setStyleSheet("background-image: url();\n"
# "color: rgb(255, 0, 0);\n"
# "background-color: rgb(255, 255, 0);\n"
# "border-radius: 20px")


    def sign_up(self):
        pymsgbox.alert(text='We dont accept new user, Sorry!', title='Wrong')

    def executeLoginPage(self):
        Dialog.close()
        run(["python3", "signup.py"])

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login Page"))
        self.remember.setText(_translate("Dialog", "Remember me"))
        self.log_in.setText(_translate("Dialog", "LOG IN"))
        self.label_3.setText(_translate("Dialog", "Not a member ?"))
        self.label_5.setText(_translate("Dialog", "Username :"))
        self.label_6.setText(_translate("Dialog", "Password :"))
        self.forgot.setText(_translate("Dialog", "Forgot Password?"))
        self.signup.setText(_translate("Dialog", "SignUp"))
        self.incorrect.setText(_translate("Dialog", "The Username or Password is incorrect !"))
        self.tryrem.setText(_translate("Dialog", "Try to remember !!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Breeze")
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
