# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from subprocess import run
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect, Qt


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 573)
        Dialog.setStyleSheet("border-radius: 0.0001px;\n"
"background-image: url(/home/alihv3000/Desktop/New Folder/bglogin.jpg);")
        Dialog.setMinimumSize(700, 573)
        Dialog.setMaximumSize(700, 573)
        Dialog.setWindowFlags(Qt.FramelessWindowHint)
        #Dialog.setAttribute(Qt.WA_TranslucentBackground)
        self.treeView = QtWidgets.QTreeView(Dialog)
        self.treeView.setGeometry(QtCore.QRect(150, 82, 401, 401))
        self.treeView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"background-image:url()\n"
"")
        self.treeView.setObjectName("treeView")
        self.treeView_2 = QtWidgets.QTreeView(Dialog)
        self.treeView_2.setGeometry(QtCore.QRect(150, 82, 401, 61))
        self.treeView_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(120, 2, 255, 255), stop:0.166 rgba(120, 2, 255, 255), stop:0.333 rgba(85, 0, 255, 255), stop:0.5 rgba(85, 0, 255, 255), stop:0.666 rgba(57, 7, 255, 255), stop:0.833 rgba(57, 7, 255, 255), stop:1 rgba(57, 7, 255, 255));\n"
"\n"
"border-radius: 0.001px;\n"
"background-image:url()")
        self.treeView_2.setObjectName("treeView_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(310, 92, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(); \n"
"background-image:url()")
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setGeometry(QtCore.QRect(260, 280, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.username.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.username.setStyleSheet("background-color: rgb(255,255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url();\n"
"border :1px solid rgb(62,62,62);\n"
"border-top-left-radius :20px;\n"
"border-bottom-left-radius : 20px; \n"
"border-top-right-radius : 20px; \n"
"border-bottom-right-radius : 20px;")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(310, 330, 221, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password.setStyleSheet("background-color: rgb(255,255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url();\n"
"border :1px solid rgb(62,62,62);\n"
"border-top-left-radius :20px;\n"
"border-bottom-left-radius : 20px; \n"
"border-top-right-radius : 20px; \n"
"border-bottom-right-radius : 20px;")
        self.password.setText("")
        self.password.setObjectName("password")
        self.log_in = QtWidgets.QPushButton(Dialog)
        self.log_in.setGeometry(QtCore.QRect(257, 392, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.log_in.setFont(font)
        self.log_in.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_in.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(120, 2, 255, 255), stop:0.166 rgba(120, 2, 255, 255), stop:0.333 rgba(85, 0, 255, 255), stop:0.5 rgba(85, 0, 255, 255), stop:0.666 rgba(57, 7, 255, 255), stop:0.833 rgba(57, 7, 255, 255), stop:1 rgba(57, 7, 255, 255));\n"
"\n"
"border-radius: 20px;\n"
"background-image:url();\n"
"")
        self.log_in.setObjectName("log_in")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(240, 440, 171, 24))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(170, 290, 81, 19))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(168, 340, 131, 20))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_6.setObjectName("label_6")
        self.signup = QtWidgets.QPushButton(Dialog)
        self.signup.setGeometry(QtCore.QRect(405, 438, 61, 27))
        self.signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup.setStyleSheet("color: rgb(85, 0, 127);\n"
"background-image:url()")
        self.signup.setObjectName("signup")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(170, 240, 81, 19))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_7.setObjectName("label_7")
        self.username_2 = QtWidgets.QLineEdit(Dialog)
        self.username_2.setGeometry(QtCore.QRect(230, 180, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.username_2.setFont(font)
        self.username_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.username_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.username_2.setStyleSheet("background-color: rgb(255,255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url();\n"
"border :1px solid rgb(62,62,62);\n"
"border-top-left-radius :20px;\n"
"border-bottom-left-radius : 20px; \n"
"border-top-right-radius : 20px; \n"
"border-bottom-right-radius : 20px;")
        self.username_2.setText("")
        self.username_2.setObjectName("username_2")
        self.password_2 = QtWidgets.QLineEdit(Dialog)
        self.password_2.setGeometry(QtCore.QRect(260, 230, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.password_2.setFont(font)
        self.password_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.password_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password_2.setStyleSheet("background-color: rgb(255,255, 255); \n"
"color: rgb(0, 0, 0);\n"
"background-image:url();\n"
"border :1px solid rgb(62,62,62);\n"
"border-top-left-radius :20px;\n"
"border-bottom-left-radius : 20px; \n"
"border-top-right-radius : 20px; \n"
"border-bottom-right-radius : 20px;")
        self.password_2.setText("")
        self.password_2.setObjectName("password_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(170, 190, 61, 19))
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image:url()")
        self.label_8.setObjectName("label_8")
        self.close = QtWidgets.QPushButton(Dialog)
        self.close.setObjectName("close")
        self.close.setGeometry(QRect(655, 12, 32, 32))
        self.close.setCursor(QtGui.QCursor(Qt.PointingHandCursor))
        self.close.setStyleSheet("border-radius: 16px;\n"
"background-image: url(/home/alihv3000/Documents/py/close-button.png);")
        self.minimize = QtWidgets.QPushButton(Dialog)
        self.minimize.setObjectName("minimize")
        self.minimize.setGeometry(QRect(615, 13, 32, 32))
        self.minimize.setCursor(QtGui.QCursor(Qt.PointingHandCursor))
        self.minimize.setStyleSheet("border-radius: 16px;\n"
"background-image: url(/home/alihv3000/Documents/py/mini.png);")

        self.retranslateUi(Dialog)
        self.log_in.clicked.connect(self.log_in.show)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username_2, self.password_2)
        Dialog.setTabOrder(self.password_2, self.username)
        Dialog.setTabOrder(self.username, self.password)
        Dialog.setTabOrder(self.password, self.log_in)
        Dialog.setTabOrder(self.log_in, self.signup)
        Dialog.setTabOrder(self.signup, self.treeView)
        Dialog.setTabOrder(self.treeView, self.treeView_2)

        self.signup.clicked.connect(self.login)
        self.close.clicked.connect(Dialog.close)
        self.minimize.clicked.connect(Dialog.showMinimized)

    def login(self):
        Dialog.close()
        run(['python3', 'login2.py'])

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign Up"))
        self.log_in.setText(_translate("Dialog", "register"))
        self.label_3.setText(_translate("Dialog", "Already have an account ?"))
        self.label_5.setText(_translate("Dialog", "Password :"))
        self.label_6.setText(_translate("Dialog", "confirm Password :"))
        self.signup.setText(_translate("Dialog", "login"))
        self.label_7.setText(_translate("Dialog", "Username :"))
        self.label_8.setText(_translate("Dialog", "Name :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Breeze')
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
